require:
  - rubocop-rails

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.1.3
  SuggestExtensions: false
  Exclude:
    - config.ru
    - Rakefile
    - db/**/*
    - vendor/**/*
    - config/**/*
    - lib/tasks/**/*
    - app/channels/**/*
    - test/**/*
    - config/environments/*
    - bin/**/*
    - spec/**/*
    - swagger/**/*

Rails:
  Enabled: true

Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/FileName:
    Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 200

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
