name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1.3']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run zeitwerk:check
      run: ./bin/rails zeitwerk:check --trace
    - name: Run rubocop
      run: bundle exec rubocop
    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql user: test
        postgresql password: password
    - name: Build app
      run: |
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:migrate RAILS_ENV=test
      env:
        DATABASE_URL: 'postgres://test:password@localhost/komik_test'
    - name: Run specs
      run: |
        bundle exec rspec
      env:
        DATABASE_URL: 'postgres://test:password@localhost/komik_test'
